### ISSUE TITLE
Requirements File, Installation Guide

### ISSUE THREAD

**Issue by charbelhass** [pannous/tensorflow-speech-recognition#6] opened 2016-06-28 12:18 UTC
Hello,

The requirements.txt file is missing, I was not able to install the project.
It would be great if we can have an installation guide.

Thanks in advance,
Regards

**Comment by dare0021** [comment] 2016-07-01 10:44
duplicate of #5

**Comment by pannous** [comment] 2016-08-23 11:18
sorry for wasting your guy's energy, it is added now.

**Closed by pannous** 2016-08-23 11:18 UTC
