### ISSUE TITLE
ValueError: No variables to save

### ISSUE THREAD

**Issue by anees042** [pannous/tensorflow-speech-recognition#22] opened 2016-12-14 07:55 UTC
I am getting error while running the examples; number_calssifier_tflearn.py and speaker_classifier_tflearn.py. below are details;

`Looking for data spoken_numbers_pcm.tar in data/
Extracting data/spoken_numbers_pcm.tar to data/
Data ready!
loaded batch of 2402 files
loaded batch of 2402 files
loaded batch of 2402 files
loaded batch of 2402 files
loaded batch of 2402 files
Traceback (most recent call last):
  File "number_classifier_tflearn.py", line 26, in <module>
    model = tflearn.DNN(net)
  File "C:\Program Files\Anaconda3\lib\site-packages\tflearn\models\dnn.py", line 57, in __init__
    session=session)
  File "C:\Program Files\Anaconda3\lib\site-packages\tflearn\helpers\trainer.py", line 125, in __init__
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1000, in __init__
    self.build()
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1021, in build
    raise ValueError("No variables to save")
ValueError: No variables to save`

AND

`15  speakers:  ['Ralph', 'Albert', 'Vicki', 'Samantha', 'Junior', 'Kathy', 'Fred', 'Princess', 'Steffi', 'Alex', 'Daniel', 'Agnes', 'Victoria', 'Tom', 'Bruce']
speakers ['Ralph', 'Albert', 'Vicki', 'Samantha', 'Junior', 'Kathy', 'Fred', 'Princess', 'Steffi', 'Alex', 'Daniel', 'Agnes', 'Victoria', 'Tom', 'Bruce']
Looking for data spoken_numbers_pcm.tar in data/
Extracting data/spoken_numbers_pcm.tar to data/
Data ready!
15  speakers:  ['Ralph', 'Albert', 'Vicki', 'Samantha', 'Junior', 'Kathy', 'Fred', 'Princess', 'Steffi', 'Alex', 'Daniel', 'Agnes', 'Victoria', 'Tom', 'Bruce']
loaded batch of 2402 files
Traceback (most recent call last):
  File "speaker_classifier_tflearn.py", line 27, in <module>
    model = tflearn.DNN(net)
  File "C:\Program Files\Anaconda3\lib\site-packages\tflearn\models\dnn.py", line 57, in __init__
    session=session)
  File "C:\Program Files\Anaconda3\lib\site-packages\tflearn\helpers\trainer.py", line 125, in __init__
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1000, in __init__
    self.build()
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1021, in build
    raise ValueError("No variables to save")
ValueError: No variables to save`

Thanks..

**Comment by pannous** [comment] 2016-12-14 20:48
duplicate of #19

**Closed by pannous** 2016-12-14 20:48 UTC
